export const FIREBASE_API_KEY = process.env["NEXT_PUBLIC_FIREBASE_API_KEY"] ?? ""
export const FIREBASE_AUTH_DOMAIN = process.env["NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"] ?? ""
export const FIREBASE_DATABASE_URL = process.env["NEXT_PUBLIC_FIREBASE_DATABASE_URL"] ?? ""
export const FIREBASE_PROJECT_ID = process.env["NEXT_PUBLIC_FIREBASE_PROJECT_ID"] ?? ""
export const FIREBASE_STORAGE_BACKET = process.env["NEXT_PUBLIC_FIREBASE_STORAGE_BACKET"] ?? ""
export const FIREBASE_MESSAGE_SENDER_ID = process.env["NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID"] ?? ""
export const FIREBASE_APP_ID = process.env["NEXT_PUBLIC_FIREBASE_APP_ID"] ?? ""
export const FIREBASE_MEASUREMENT_ID = process.env["NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"] ?? ""

export const SITE_URL = process.env["NEXT_PUBLIC_SITE_URL"] ?? ""

export const AUTHENTICATION_PASS = process.env["NEXT_PUBLIC_AUTHENTICATION_PASS"]